name: API Functional Tests (Newman)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Testing Repository
        uses: actions/checkout@v4

      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
          repository: abiiemmm/warung-kasir
          path: server

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      - name: Create .env File
        working-directory: ./server
        run: |
          echo "PORT=3000" > .env
          echo "NODE_ENV=test" >> .env
          echo "MONGO_URI=mongodb://127.0.0.1:27017/warung-kasir" >> .env
          echo "DATABASE_URL=mongodb://127.0.0.1:27017/warung-kasir" >> .env
          echo "JWT_SECRET=supersecretkeyforportfolio123" >> .env

      - name: Build Next.js App
        working-directory: ./server
        run: npm run build

      - name: Start Backend Server
        working-directory: ./server
        run: npm start > server.log 2>&1 &

      - name: Wait for Server Port
        run: npx wait-on http-get://127.0.0.1:3000 --timeout 30000

      - name: Print Server Log on Failure
        if: failure()
        run: cat server/server.log

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection with Newman
        run: |
          newman run "postman/Test Warung-Kasir.postman_collection.json" -e "postman/New Environment.postman_environment.json"